# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e4b13abde0c8e771dcfa5c2c099fab795344b5d695403560a33d5b612a3fb664389afc3e46c925b144a2089afd91c8590b777cc220061d969087a51196fb64

test:
  secret_key_base: 272d6b425039fb0dd07fa14a2ae3214671fca5ffccaa92d31ac41807c484e313eabe1f2916b9a4e0383727e7d6c636da3b23bebebd9a8f405de62d7ed19d940b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
